apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/pgadmin

patches:
  - path: ./deployment-patch.yaml
    target:
      kind: Deployment
      name: pgadmin
  - path: ./ingress-patch.yaml
    target:
      kind: Ingress
      name: pgadmin-ingress
  - path: ./configmap-patch.yaml
    target:
      kind: ConfigMap
      name: pgadmin-config
