apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/sonar
patches:
  - path: ./configmap-patch.yaml
    target:
      kind: ConfigMap
      name: sonar-config
  - path: ./ingress-patch.yaml
    target:
      kind: Ingress
      name: sonar-ingress
