apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/postgres

patches:
  - path: ./configmap-patch.yaml
    target:
      kind: ConfigMap
      name: postgres-config
  - path: ./persistent-volume-patch.yaml
    target:
      kind: PersistentVolume
      name: postgres-pv
  - path: ./persistent-volume-claim-patch.yaml
    target:
      kind: PersistentVolumeClaim
      name: postgres-pvc
